exclude:
- CNAME
- Gemfile
- Gemfile.lock
- vendor
- "*.iml"
- fetch_yt_preview

highlighter: rouge
markdown: kramdown

external: https://foosel.net
#external: http://192.168.1.3:4000
baseurl: ""

title : Gina Häußge
description: Software Architect & Full Stack Developer

author:
  name: Gina Häußge
  pronunciation: "[dʒiːna hɔʏsɡə]"
  profession: Software Architect & Full Stack Developer
  social:
  - name: LinkedIn
    icon: fa-linkedin
    url: https://www.linkedin.com/in/ginahaeussge
  - name: Twitter
    icon: fa-twitter
    url: https://twitter.com/foosel
  - name: Github
    icon: fa-github-alt
    url: https://github.com/foosel
  - name: Mail
    icon: fa-envelope
    url: "mailto:contact@foosel.net"
    notarget: true
  skills:
  - '#python'
  - '#javascript'
  - '#java'
  - '#3dprinting'
  - '#octoprint'
  - '#iot'
  twitter: foosel
  github: foosel
  avatar: /assets/img/card.jpg

sidebar:
  links:
    - name: Home
      link: /
    - name: Media
      link: /media/
    - name: Legal Notice
      link: /imprint/
      rel: nofollow
    - name: Privacy Policy
      link: /privacy/
      rel: nofollow

plugins:
  - jekyll-redirect-from
