exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "node_modules"]
highlighter: rouge
markdown: kramdown

external: https://foosel.net
#external: http://192.168.1.3:4000
baseurl: ""

title : Gina Häußge
description: Software Architect & Full Stack Developer

author:
  name: Gina Häußge
  profession: Software Architect & Full Stack Developer
  social:
  - name: LinkedIn
    icon: fa-linkedin
    url: https://www.linkedin.com/in/ginahaeussge
  - name: Github
    icon: fa-github-alt
    url: https://github.com/foosel
  - name: Google+
    icon: fa-google-plus
    url: https://plus.google.com/+GinaHäußge
  - name: Twitter
    icon: fa-twitter
    url: https://twitter.com/foosel
  - name: Mail
    icon: fa-envelope
    url: "mailto:gina@foosel.net"
    notarget: true
  skills:
  - '#python'
  - '#javascript'
  - '#java'
  - '#3dprinting'
  - '#octoprint'
  - '#iot'
  twitter: foosel
  github: foosel
  avatar: /assets/img/card.jpg

sidebar:
  links:
    - name: Home
      link: /
    - name: Imprint
      link: /imprint/