version: '3'

vars:
  TERMUX: '{{and .PREFIX (contains "com.termux" .PREFIX)}}'
  TODAY: '{{now | date "2006-01-02"}}'

tasks:
  serve:
    desc: Runs hugo serve, all posts visible.
    cmds:
      - hugo serve -D -E -F {{if .TERMUX}}--noBuildLock{{end}}

  new-blog:
    desc: Creates a new blog post.
    vars:
      TITLE: '{{.CLI_ARGS}}'
      SLUG: '{{trimall "-" (regexReplaceAll "--+" (regexReplaceAll "[^A-Za-z0-9-]" (regexReplaceAll "\\s+" (lower .TITLE) "-") "") "-")}}'
    cmds:
      - |
        path="content/blog/{{.TODAY}}-{{.SLUG}}"
        mkdir $path

        file="$path/index.md"
        cat > $file <<EOF
        ---
        title: "{{.TITLE}}"
        #description:
        date: {{.TODAY}}
        cover:
          image: cover.jpg
          alt: Add cover.jpg at ~1200x600px and describe it here
          relative: true
        draft: true
        ---
        
        EOF
        echo $file

  new-til:
    desc: Creates a new TIL post.
    vars:
      TITLE: '{{.CLI_ARGS}}'
      SLUG: '{{trimall "-" (regexReplaceAll "--+" (regexReplaceAll "[^A-Za-z0-9-]" (regexReplaceAll "\\s+" (lower .TITLE) "-") "") "-")}}'
    cmds:
      - |
        file="content/til/{{.SLUG}}.md"
        cat > $file <<EOF
        ---
        title: "{{.TITLE}}"
        date: {{.TODAY}}
        tags: []
        draft: true
        ---
        
        EOF
        echo $file
