name: Publish to Github Pages

on:
    push:
        branches:
            - master

jobs:
    build-and-publish:
        name: Publish to Github Pages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "14.0"

            - name: Install dependencies
              run: npm install

            - name: 🔨 Build
              run: npm run export

            - name: 🚀 Deploy page
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: published
                  publish_dir: ./out
                  enable_jekyll: false
                  user_name: "github-actions[bot]"
                  user_email: "github-actions[bot]@users.noreply.github.com"
